//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class trabajador
    {
        public int id_trabajador { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public decimal sueldo { get; set; }
        public string categoria { get; set; }
    }
}
